name: Go

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Staticcheck
      run: |
        pwd
        echo ${GOPATH}
        echo ${GOROOT}
        GOBIN=$PWD/bin sudo go install honnef.co/go/tools/cmd/staticcheck
        echo ${GOBIN}
        cd ${GOROOT}/bin
        ls
      
